# Generated by Django 5.1.2 on 2025-09-08 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone format.', regex='^\\+?\\d{7,15}$')])),
                ('university', models.CharField(blank=True, default='', max_length=160)),
                ('major', models.CharField(blank=True, default='', max_length=160)),
                ('study_level', models.CharField(blank=True, default='', max_length=80)),
                ('duration', models.CharField(choices=[('1m', '1 month'), ('2m', '2 months'), ('3m', '3 months'), ('other', 'Other')], default='1m', max_length=8)),
                ('track', models.CharField(choices=[('marketing', 'Digital Marketing'), ('design', 'Graphic Design'), ('content', 'Content Creation'), ('photo', 'Photography & Video'), ('other', 'Other')], default='marketing', max_length=20)),
                ('experience_text', models.TextField(blank=True, default='')),
                ('goal', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('teamwork', models.CharField(blank=True, default='', max_length=16)),
                ('challenge', models.TextField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='careers/intern_cv/')),
                ('consent', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('shortlist', 'Shortlisted'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=12)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['email'], name='careers_int_email_91ecfb_idx'), models.Index(fields=['status'], name='careers_int_status_fb2349_idx'), models.Index(fields=['university'], name='careers_int_univers_411a76_idx'), models.Index(fields=['track'], name='careers_int_track_e2e1a0_idx'), models.Index(fields=['created_at'], name='careers_int_created_aedc81_idx')],
            },
        ),
        migrations.CreateModel(
            name='TalentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone format.', regex='^\\+?\\d{7,15}$')])),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='careers/talent_cv/')),
                ('consent', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('shortlist', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=12)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['email'], name='careers_tal_email_e973a5_idx'), models.Index(fields=['status'], name='careers_tal_status_28a1ed_idx'), models.Index(fields=['created_at'], name='careers_tal_created_b59ece_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
