version: "3.9"
services:
  web:
    build: .
    command: >
      bash -lc
      "python manage.py makemigrations --noinput && 
       python manage.py migrate --noinput &&
       python manage.py collectstatic --noinput &&
       gunicorn true.wsgi:application -c gunicorn.conf.py"
    environment:
      DJANGO_SETTINGS_MODULE: true.settings
      DEBUG: "1"
      DATABASE_URL: "postgresql://postgres:mkYtokmktyUdYlGTPCkhAxzkiyiKQLnp@ballast.proxy.rlwy.net:15226/railway"
      DB_SSL_REQUIRE: "1"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      CSRF_TRUSTED_ORIGINS: "http://localhost"
    ports:
      - "8000:8000"

