# Generated by Django 5.2.4 on 2025-08-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='الوصف (عربي)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ar',
            field=models.CharField(default=123, max_length=120, verbose_name='الاسم (عربي)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(default=123, max_length=120, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشِط'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع'),
        ),
    ]
