# Generated by Django 5.2.4 on 2025-08-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_remove_partner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_ar',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
