# Generated by Django 5.2.5 on 2025-09-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
    ]
