# Generated by Django 5.2.4 on 2025-08-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_remove_service_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='prefer_lang',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], db_index=True, default='en', max_length=5),
        ),
    ]
