# Generated by Django 5.2.4 on 2025-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicerequest_prefer_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
