# Generated by Django 5.2.4 on 2025-08-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_options_remove_service_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
