# Generated by Django 5.2.4 on 2025-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_price_service_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default=31231, max_length=255),
            preserve_default=False,
        ),
    ]
