# Generated by Django 5.1.2 on 2025-07-05 08:32

import authentiocation.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentiocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentiocation.models.UserManager()),
            ],
        ),
    ]
