# Generated by Django 5.1.2 on 2025-07-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentiocation', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
