# Generated by Django 5.1.2 on 2025-07-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentiocation', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
