# Generated by Django 5.2.4 on 2025-08-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentiocation', '0005_user_date_joined_user_role_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
