# Generated by Django 5.2.4 on 2025-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentiocation', '0007_alter_user_options_user_role_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
