# Generated by Django 5.2.5 on 2025-09-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_review_options_remove_review_reviewer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name_ar',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name_en',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='course_instructors/'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
