# Generated by Django 5.2.5 on 2025-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_end_date',
            field=models.DateField(blank=True, help_text='Last date for enrollment/registration', null=True),
        ),
    ]
