# Generated by Django 5.2.5 on 2025-09-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_registration_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_ar',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
