# Generated by Django 5.2.5 on 2025-09-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_created_at_alter_course_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
