# Generated by Django 5.1.2 on 2025-09-08 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendance_mode',
            field=models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='in_person', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='ILS', max_length=6),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='location_ar',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='location_en',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Optional SEO slug', max_length=255),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['attendance_mode'], name='courses_cou_attenda_010d55_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_3c7e41_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gte', 1), _connector='OR'), name='course_capacity_positive'),
        ),
    ]
