# Generated by Django 5.2.4 on 2025-08-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='sort_order',
        ),
    ]
