# Generated by Django 5.1.2 on 2025-07-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='project_url',
        ),
    ]
