# Generated by Django 5.2.4 on 2025-08-26 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolioitem_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='image',
            new_name='image_cover',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioitem')),
            ],
        ),
    ]
