# Generated by Django 5.2.4 on 2025-08-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_description_portfolioitem_description_ar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
