# Generated by Django 5.2.4 on 2025-08-26 17:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_portfolioimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='description_ar',
            new_name='challenge_ar',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='description_en',
            new_name='challenge_en',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='results_ar',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='results_en',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='solution_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='solution_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption_ar', models.CharField(blank=True, max_length=255)),
                ('caption_en', models.CharField(blank=True, max_length=255)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio Image',
                'verbose_name_plural': 'Portfolio Images',
            },
        ),
    ]
