# Generated by Django 5.2.4 on 2025-08-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolioitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='challenge_ar',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='challenge_en',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='solution_ar',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='solution_en',
        ),
    ]
