# Generated by Django 5.2.5 on 2025-09-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_portfolioitem_challenge_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='results_ar',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='results_en',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/covers/'),
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
